### ISSUE TITLE
bug in cleanup

### ISSUE THREAD

**Issue by yelizariev** [odoo/odoo-extra#101]
https://github.com/odoo/odoo-extra/blob/master/runbot/runbot.py#L1156

it states

        # cleanup: find any build older than 7 days.

but searchs builds that **not** older than 7days:

               AND (state != 'done' OR job_end > (now() - interval '7 days'))

@KangOl check this please. It was from your commit https://github.com/odoo/odoo-extra/commit/17ba57fe4573acadb532a6e2df1d0cf300f864c0

**Comment by yelizariev** [comment]
Correct link to the commit: https://github.com/odoo/odoo-extra/commit/3e4eaa13e0f16877e9363c41c74c01589875a3c2

**Comment by KangOl** [comment]
Exactly, it search active build (thus the variable name)

**Comment by yelizariev** [comment]
Got it! 
I felt that it's very simple and something is wrong in my understanding...

Thank you.
