### ISSUE TITLE
fast_launch route fails on 9.0 branches

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo-extra#103]
http://runbot.odoo.com/runbot/1/8.0  works (fast_launch route), but http://runbot.odoo.com/runbot/1/9.0  gives a 404. 

Faulty line is probably https://github.com/odoo/odoo-extra/blob/master/runbot/runbot.py#L1557 but I'm not sure what parameters are expected in v9.

**Comment by Yajo** [comment]
STR?

**Comment by gurneyalex** [comment]
@Yajo can you expand the acronym? :smile_cat:

**Comment by Yajo** [comment]
Steps to reproduce?

**Comment by gurneyalex** [comment]
Odoo change causing the failure on runbot seems to be https://github.com/odoo/odoo/commit/afa9f4b

**Comment by gurneyalex** [comment]
@Yajo click on both links: the first one works, the second does not

**Comment by antespi** [comment]
This is also a bug in Odoo runbot
OK (v8): http://162177-8-0-6742d1.runbot.odoo.com/login?db=162177-8-0-6742d1-all&login=admin&key=admin&redirect=/web?debug=1
FAIL (v9): http://162183-9-0-5f97e9.runbot.odoo.com/login?db=162183-9-0-5f97e9-all&login=admin&key=admin&redirect=/web?debug=1

**Comment by gurneyalex** [comment]
This is the patch I deployed on the OCA's runbot:

```
@@ -1512,7 +1513,12 @@ class RunbotController(http.Controller):
             if last_build.state != 'running':
                 url = "/runbot/build/%s?ask_rebuild=1" % last_build.id
             else:
-                url = ("http://%s/login?db=%s-all&login=admin&key=admin%s" %
+                
+                if build.branch_id.branch_name.startswith('9.0'):
+                    base_url = "http://%s/web/login?db=%s-all&login=admin&key=admin%s"
+                else:
+                    base_url = "http://%s/login?db=%s-all&login=admin&key=admin%s"
+                url = (base_url %
                        (last_build.domain, last_build.dest, "&redirect=/web?debug=1" if not build.branch_id.branch_name.startswith('7.0') else ''))
```
It at leasts prevents the 404 error.

@sylvain-garancher confirmed that the automatic login feature was removed in 9.0, so we probably won't get anything better unless we patch stuff on runbot.

**Comment by gurneyalex** [comment]
@antespi my point exactly, hence my reporting here :smile_cat:

**Comment by antespi** [comment]
:+1: for @gurneyalex patch. I think this backdoor (auto logging) is not available anymore.
Other way would be to make an addon with this controller to make it available again.

**Comment by rafaelbn** [comment]
:+1:

**Comment by odony** [comment]
The automatic login feature was removed on purpose because it needlessly increases the attack surface of Odoo. A route that lets you force-login a browser with a simple GET request is a perfect target for secondary attacks through XSS, CSRF, etc. If you're annoyed by the 404 error, patching runbot is the way to go indeed, so we can discuss it on #104.
