### ISSUE TITLE
After I run a test which “fails” I can’t see any log that shows me what is wrong

### ISSUE THREAD

**Issue by andrewyova** [odoo/odoo-extra#111]
--------------------------------------------------------How I installed Runbot--------------------------------------------
1. Sudo apt-get install -y python-matplotlib
2. Sudo apt-get install -y font-manager
After finish install i switch user - - > switch user to “odoo9c” - > mine
1. Mkdir ~/.ssh
2. Chmod 700 ~/.ssh
3. Ssh-keygen -t rsa -b 4096 -C “myemail@email.com”
I insert keygen at my dir  /opt/odoo/odoo9c/.ssh/id_rsa 
After insert i leave passphrase empty
Open ssh key - - > cat /opt/odoo9c/.ssh/id_rsa.pub
I copy that key to add my ssh key at gitlab
Ssh - T git@gitlab.com
After finish i download runbot at https://github.com/odoo/odoo-extra

I login using my odoo user : odoo9c at open odoo local like this
/opt/odoo9c/openerp-server --addons-path=/opt/odoo9c/addons, --xmlrpc-port 8100 (I add runbot addons at /opt/odoo9c/addons)
I open localhost:8100 and create new database called runbot

After create and login i start install app (base setup,web,runbot)
this is a setting repository on runbot that i create :

- Field [Modules to install ] is “stock” 
- Field [ mode ] is default : Poll
- Field [ Nginx ] not check
- Field [ Duplicate repo ] is empty
- Field [ Extra dependencies] is empty
- Field [ modules to install ] is empty
- Field [ Other modules to install automatically ] is default “Repository modules (excluding dependencies)” 
- Field at Github token is empty
- Field at Limited to group is empty
- Last hook time is empty

i save it and update and i see the repository being tested, after finish tested the result is red (thumbs down) 
when i click log it show no error log 

In the folder: /opt/odoo9c/addons/runbot/static/build/00002-testing-pci-sales-discount-76e00b/logs

file job_10_test_base.txt : [/usr/bin/python: can't open file '/opt/odoo9c/addons/runbot/static/build/00002-testing-pci-sales-discount-76e00b/bin/openerp-server.py': [Errno 2] No such file or directory]

Would you have any detailed documentation on How Runbot works (how it tests a build, what makes a build pass or fail?)

**Comment by moylop260** [comment]
What is your odoo-extra sha and what is the repository record?

**Comment by andrewyova** [comment]
what do you mean about odoo-extra sha? 
- > i download odoo-extra witch at branch 9.0
- > which repository record? i add repository record at my project gitlab

**Comment by mart-e** [comment]
Hello,

You may want to check these two presentations
https://www.odoo.com/slides/slide/how-to-setup-your-own-runbot-309
https://www.odoo.com/slides/slide/deploy-own-runbot-to-build-a-dashboard-449

The runbot [does not find](https://github.com/odoo/odoo-extra/blob/9a185fc9d0f1f77225d0b57a3697761d458a49f6/runbot/runbot.py#L872-L885) your Odoo server executable.

**Comment by andrewyova** [comment]
@mart-e 
so i must add repository git@github.com:odoo/odoo ,save and update it?
that repository it's to much take time , how many size that repository?

**Comment by mart-e** [comment]
@andrewyova you need a full odoo repository to run your modules on to (and it is not the same than the server the runbot uses). Either the official or your fork.
Yes, it will take time and yes it will take a lot of space, this is why we advise to use a dedicated server for the runbot.

Closing as a configuration issue and not an issue on the runbot code.

[Another tutorial with numbers for the required resources](http://www.odoo.yenthevg.com/installing-and-configuring-your-own-runbot/)
