### ISSUE TITLE
[CLEANING] move unsupported addons to another repo

### ISSUE THREAD

**Issue by rim-odoo** [odoo/odoo-extra#129]
As this repo is mainly used to maintain runbot + runbot-related issues, can we:
- [ ] move all the old unsupported addons to another repo (`odoo/oldstuff`)
- [ ] rename this one into `odoo/runbot`

**Comment by mart-e** [comment]
The runbot has been moved to https://github.com/odoo/runbot. Long live runbot!

**Comment by mart-e** [comment]
and @d-fence should probably remove it from here :wink:

**Comment by rim-odoo** [comment]
@mart-e hurray!

I would lock this old repo since there is nothing maintained here anymore (addons from v8 and older)
