### ISSUE TITLE
plugin_outlook install error

### ISSUE THREAD

**Issue by alexteodor** [odoo/odoo-extra#47]
in plugin_outlook.xml   line 56 coment till 71.
it-s a inherit view in settings, configuration sales. It has almost no purpose. and also is missing a field in plugin_outlook.py. 

Element '<div name="module_plugin_outlook">' cannot be located in parent view

the problem in plugin_outlook.py can be solved ( but it;s not necesary if you do not want the view)
class sale_config_settings(osv.osv):
    _inherit = 'sale.config.settings'
    _columns ={
	'module_plugin_outlook': fields.boolean ('module_plugin_outlook'),
}

**Comment by rim-odoo** [comment]
From https://github.com/odoo/odoo-extra/blob/master/README.md

"This repository holds an archive of Odoo modules that are not maintained anymore by the publisher. Use them at your own risk."
