### ISSUE TITLE
Thunderbird plugin for v 8.0 gives error when installed

### ISSUE THREAD

**Issue by jalzaga** [odoo/odoo-extra#68]
Module: plugin_thunderbird
Version 8.0.1.0
Error details:
Element '\<div name="module_plugin_thunderbird">' cannot be located in parent view

Error context:
View `Sales Application`
[view_id: 1068, xml_id: n/a, model: sale.config.settings, parent_id: 208]" while parsing /opt/odoo/odoo/addons/plugin_thunderbird/plugin_thunderbird.xml:54, near

\<record id="view_config_thunderbird_installer" model="ir.ui.view">
            \<field name="name">Sales Application</field>
            \<field name="model">sale.config.settings</field>
            \<field name="inherit_id" ref="base_setup.view_sale_config_settings"/>
            \<field name="arch" type="xml">
                \<div name="module_plugin_thunderbird" position="replace">
                    \<div>
                        \<field name="module_plugin_thunderbird" class="oe_inline"/>
                        \<label for="module_plugin_thunderbird"/>
                        \<button name="%(action_thunderbird_installer)d" type="action" string="Download and install the plug-in" icon="gtk-execute" attrs="{'invisible': [('module_plugin_thunderbird','=',False)]}" class="oe_link"/>
                    \</div>
                \</div>
            \</field>
        \</record>

**Comment by rim-odoo** [comment]
From https://github.com/odoo/odoo-extra/blob/master/README.md 

"This repository holds an archive of Odoo modules that are not maintained anymore by the publisher. Use them at your own risk."
