### ISSUE TITLE
Why website_multi in odoo-extra?

### ISSUE THREAD

**Issue by rafaelbn** [odoo/odoo-extra#70]
Hi,

I would like to know why module website_multi is in https://github.com/odoo/odoo-extr a not in https://github.com/odoo/odoo

It is very useful for clients to create different landing pages with different domains in the same database.

I can see that this module is not in master

Thanks
Regards
Rafael

**Comment by mart-e** [comment]
Hello,

Check the following thread where we answered this question:
https://www.odoo.com/groups/community-59/community-12256428?mode=thread&date_begin=&date_end=

Regards
